kubevirt/ipam-extensions

- .github/workflows/publish-img.yaml
This way, we're more efficient with the size of the registry.
> ci, img build: build a latest image

- Makefile
- pkg/ipamclaimswebhook/podmutator.go
- pkg/vmnetworkscontroller/controller_test.go
- remove CRD generation related operations (from the Makefile). Those are not needed because we don't ship a CRD
- remove a duplicated test
- allow the admission webhook to understand both types of KubeVirt VM.spec.network.multus network names (with and without the namespace)
- add some logging to the admission webhook code. A follow up PR will add logging level support, so the user can specify the verbosity of the controller / webhook.
> Assorted alpha release improvements

- pkg/vmnetworkscontroller/controller.go
We were using `corev1`, which should be used for core Kubernetes imports, like pods.
> controller: use metav1 import

- cmd/main.go
All virt-launcher pods have this label, as can be seen in the virt-controller templating code: [0].
By only caching these pods, our controller will use a lot less memory.
[0] - https://github.com/kubevirt/kubevirt/blob/913c158a951736c1c9a5054a102680996ff07440/pkg/virt-controller/services/template.go#L1509
> perf: only cache virt-launcher pods

- dist/install.yaml
When PR #12 was added, we forgot to generate the new installer manifests.
This commit generates them.
Fixes #15
> bug, config: fix RBAC to allow IPAMClaim updates

- cmd/main.go
In OpenShift, the certificates are not mounted in the default path, and need to be overridden.
> cmd, webhook: add config opt to specify the cert path

- hack/cluster.sh
It allows custom args,
for example skipping kubevirt installation
(which comes with ipam manager by OVN-k8s kind.sh)
The user would be able to install custom
kubevirt and ipam manager this way.
`export KIND_ARGS="-ic -i6 -mne"`
> cluster: Allow custom kind args

- .github/workflows/checks.yaml
- .github/workflows/publish-img.yaml
- PROJECT
- README.md
- cmd/main.go
- config/certmanager/certificate.yaml
- config/default/kustomization.yaml
- config/default/manager_config_patch.yaml
- config/default/manager_webhook_patch.yaml
- config/default/webhookcainjection_patch.yaml
- config/manager/kustomization.yaml
- config/manager/manager.yaml
- config/rbac/leader_election_role.yaml
- config/rbac/leader_election_role_binding.yaml
- config/rbac/role.yaml
- config/rbac/role_binding.yaml
- config/rbac/service_account.yaml
- config/webhook/service.yaml
- dist/install.yaml
- go.mod
- pkg/ipamclaimswebhook/podmutator.go
- pkg/vmnetworkscontroller/controller.go
- test/e2e/e2e_suite_test.go
- test/e2e/persistentips_test.go
- test/go.mod
This PR renames the org and repo
so we will adapt to the transfer under `kubevirt/ipam-extensions`.
It renames the controller to `kubevirt-ipam-controller`.
It also rename resources named `controller-manager` to `manager`
so once the prefix of `kubevirt-ipam-controller-` is added, it won't be
`kubevirt-ipam-controller-controller-manager`
Note: we will need please a new tag on the new repo, so we can use the new image location.
> Transfer repo and rename to kubevirt-ipam-controller

- cmd/main.go
- pkg/vminetworkscontroller/vmi_controller.go
- pkg/vminetworkscontroller/vmi_controller_test.go
It reconciles VMI not VM, hence rename accordingly.
Rename folder, files and package accordingly.
Fixes #
**Checklist**
```release-note
```
> Rename VMI reconciler

- pkg/vminetworkscontroller/vmi_controller.go
Fixes #
**Checklist**
```release-note
None
```
> vmi controller: Add missing error handling

- pkg/vminetworkscontroller/vmi_controller.go
- pkg/vminetworkscontroller/vmi_controller_test.go
In case claim already exists,
need to compare to the expected UID
which might belong either to the VM or VMI,
depending if the VMI has owner VM or standalone.
Fixes #
**Checklist**
```release-note
None
```
> vmi controller: Fix UID comparison

- pkg/vminetworkscontroller/vmi_controller.go
Currently looking for matching ipam claims is done only
according the owning VM name.
It means that when removing finalizer, we will remove
the finalizer from ipam claims with the same owning VM name across
all namespaces, which is wrong.
Fix it by limiting the search to the specific VM namespace.
Fixes #
**Checklist**
```release-note
None
```
> claims: Filter ipamclaim lookup according namespace

- Makefile
- hack/cluster.sh
Starting tests before it stabilize might add noise.
Fixes #
**Checklist**
```release-note
```
> cluster: Wait for component deployment to stabilize

- pkg/vminetworkscontroller/vmi_controller.go
- pkg/vminetworkscontroller/vmi_controller_test.go
We don't need to create claims for them,
As done already on the webhook as well.
Fixes #
**Checklist**
```release-note
```
> claims: Filter out Multus Default networks

- .github/workflows/publish-img.yaml
- Makefile
- hack/cluster.sh
- passt/Dockerfile
- passt/passt-binding-cni-ds.yaml
Include DaemonSet manifest to deploy the binary on the cluster nodes.
Fixes #
**Checklist**
```release-note
```
> passt: Build and publish Passt binding CNI image

- cmd/main.go
- pkg/claims/claims.go
- pkg/vminetworkscontroller/vmi_controller.go
- pkg/vminetworkscontroller/vmi_controller_test.go
- pkg/vmnetworkscontroller/vm_controller.go
- pkg/vmnetworkscontroller/vm_controller_test.go
- test/e2e/persistentips_test.go
- test/env/matcher.go
Remove the finalizer from the ipam claim on the following cases:
VMI events:
1. VM that is marked for deletion, and its VMI is gone.
2. Standalone VMI, that is marked for deletion, and it's virt-launcher is gone.
3. Standalone VMI that was deleted.
VM events:
1. VM is deleted (happens on background delete).
2. VM is marked for deletion, and the VMI is deleted (foreground delete).
(might remind VMI events, but it can happen for stopped VM so we should handle
it as well as VM event).
Changes beside that:
1. Add missing `BlockOwnerDeletion` that affects foreground delete.
Owner which is either VM or VMI, will be deleted only after the
owned ipam claim is deleted.
We remove the finalizer from the ipam claim, once the claim is ready to be deleted.
2. Add …
> Fix Finalizer logic

- config/rbac/role.yaml
- dist/install.yaml
Lately `blockOwnerDeletion` was added (finalizer fix PR).
On OpenShift there is an additional protection, that setting `blockOwnerDeletion` requires
to be able to set finalizers on the owner.
The owner might be either VM or VMI.
Add the missing rbacs.
```
2024-08-11T10:41:43Z	ERROR	Reconciler error	{"controller": "virtualmachineinstance", "controllerGroup": "kubevirt.io", "controllerKind": "VirtualMachineInstance", "VirtualMachineInstance": {"name":"vma-localnet-ipam-medium-pool","namespace":"localnet-ipam"}, "namespace": "localnet-ipam", "name": "vma-localnet-ipam-medium-pool", "reconcileID": "9d6cb8f1-87be-410b-8b92-3efce065cd2d", "error": "ipamclaims.k8s.cni.cncf.io \"vma-localnet-ipam-medium-pool.ipam-network\" is forbidden: cannot set …
```
> Add missing rbacs

- cmd/main.go
This PR prunes the unnecessary pod information before caching it in the informer.
We only need a subset of the metadata present in the pods, and we for sure do not care about its spec or status.
Fixes #
This PR supersedes #14 
**Checklist**
```release-note
Cache only the required metadata for pods, thus using a lot less memory.
```
> Cache minimal data

- .github/workflows/checks.yaml
- test/e2e/e2e_suite_test.go
- test/e2e/persistentips_test.go
Collect k8s logs upon errors to ease debugging.
For more info see https://github.com/actions/upload-artifact
Fixes #
It assume there are no parallel runs of the tests (it cleans the logs folder).
Each error would consume around 0.5Mb zipped.
We might want to consider reducing the retention, so it wont limit us
but on the other hand this repo isn't super active / flaky, so we can just be proactive.
Tested on CI by injecting an error.
Upon needs we can add logs (i.e virt-launcher), describe VMIs and so on.
```release-note
```
> e2e: Collect git action data in case of a failure

- Makefile
- hack/cluster.sh
In order to allow `cluster-sync` for providers that were not
created by the default scripts in this repo,
allow setting custom `KUBECONFIG` which is all needed
for `cluster-sync` and `test-e2e` targets.
Fixes #
```release-note
```
> Allow setting custom KUBECONFIG

- hack/cluster.sh
Use rollout instead of wait at `make cluster-sync`
**Which issue(s) this PR fixes** 
Fixes #61
```release-note
NONE
```
> cluster-sync: Use rollout instead of wait

- pkg/claims/claims.go
- pkg/config/types.go
- pkg/ipamclaimswebhook/podmutator.go
- pkg/ipamclaimswebhook/podmutator_test.go
- pkg/udn/primary_network.go
- pkg/vminetworkscontroller/vmi_controller.go
- pkg/vminetworkscontroller/vmi_controller_test.go
This PR add support for ovn-kubernetes primary networks by doing a pair of things:
- Creating an IPAMClaim if there is a primary network at namespace
- Annotating the virt-launcher pod with  `k8s.ovn.org/ovn-udn-ipamclaim-reference`
TODO:
```release-note
Support ovn-kubernetes primary network feature.
```
> Support primary network

- pkg/config/types.go
- pkg/ipamclaimswebhook/podmutator_test.go
This PR renames the annotation used to match the annotation expected [in this OVN-Kubernetes PR](https://github.com/ovn-org/ovn-kubernetes/pull/4651/).
In the future, we may actually use a label, and this name might change.
We expect to define this in this [OpenShift enhancement](https://github.com/openshift/enhancements/pull/1673).
Fixes #
```release-note
```
> udn: rename the annotation used

- .github/workflows/checks.yaml
- .gitignore
- test/e2e/e2e_suite_test.go
Due to https://github.com/actions/upload-artifact/issues/602
Hidden folders are skipped.
We are using `.output`, so it was skipped and artifacts were not collected in case of an error.
Rename it to fix the problem.
Fixes #
```release-note
```
> e2e: Fix artifacts collecting

- pkg/udn/primary_network.go
- pkg/vminetworkscontroller/vmi_controller_test.go
udpn: Add missing error wrapping
```release-note
udpn: Add missing error wrapping
```
> udpn: Add missing error wrapping

- hack/cluster.sh
Make cluster-sync going to install it anyhow.
Fixes #
```release-note
```
> cluster: Use --opt-out-kv-ipam

- pkg/ipamclaimswebhook/podmutator_test.go
Since the patches might appear in different order on some cases
we should use `ConsistOf` on those cases, and keep `Equal` by default,
since the patches are applied in order.
Example
https://github.com/kubevirt/ipam-extensions/actions/runs/10900433841/job/30248013978?pr=68
Fixes #
```release-note
```
> pod mutator, unit tests: Fix flaky test

- .github/workflows/checks.yaml
- .github/workflows/publish-img.yaml
ubuntu-latest now uses Ubuntu 24.04, while it used to use 22.04. To unblock Github CI in the short term, we set it to ubuntu-22.04.
It has been observed that build actions, such as free disk space, are broken
with ubuntu-latest, which now points to Ubuntu 24.04. To resolve this,
we are switching to the ubuntu-22.04 tag, which was previously used by ubuntu-latest.
Fixes #
Please check error logs on PR: https://github.com/kubevirt/ipam-extensions/pull/78
please check issue: https://github.com/actions/runner-images/issues/10636
```release-note …
```
> Set the GitHub runner image to Ubuntu 22.04 explicitly.

- config/manager/manager.yaml
- dist/install.yaml
This PR specifies the deployment's priority class, thus assuring the component is not preempted for other workloads with lesses priority. 
Fixes #
```release-note
Specify the kubevirt-cluster-critical priorityClass for this deployment. It requires KubeVirt to be deployed.
```
> template: specify priority class

- README.md
The .spec.running field is deprecated, therefore we should runStrategy instead.
For more info, look at:
kubevirt/kubevirt#11993
Fixes #
```release-note
NONE
```
> README: Remove usage of deprecated .spec.running field

- test/e2e/persistentips_test.go
Use `managedTap` binding instead `Passt` for primary UDN.
It is registered as part of OVN kind.sh that we use in this repo to spin the cluster.
Fixes #
Currently only IPv4 is supported.
A follow-up will add IPv6 support, by adding it to cloud-init, and deploying a dual stack cluster.
Once OVN use `l2bridge` naming we will adapt as well.
```release-note
None
```
> UDN: Use managedTap instead passt

- .github/workflows/checks.yaml
- .github/workflows/publish-img.yaml
…ntu images.
Build actions, including free disk space, are broken on ubuntu-latest, which now points to Ubuntu 24.04. To resolve this, we have removed the non-existent package from ubuntu-latest.
Fixes #
We are making these changes to align with the updates in OVN-Kubernetes, as seen in [PR #4920](https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4920).
```release-note
None
```
> Remove non-existent package msbuild in latest ubuntu images

- test/e2e/persistentips_test.go
- test/env/getter.go
- test/env/matcher.go
Currently in the e2e persistent-ips the method of retrieving the IPs from the VM differs between primary and secondary UDN VMs. The reason for the difference is that primary UDN VMs did not support publishing the IPs via VMI.status.
Due to improvements in kubevirt/kubevirt the interface on vmi.status (https://github.com/kubevirt/kubevirt/pull/13018) the vmi interface is now published on the vmi.status - also for primary UDN VMs. 
Changing the primary UDN e2e function that retrieves the IPs to use the vmi.status allows us to simplify the e2e by unifying the function that retrieves the VMI IPs.  …
> e2e, persistent-ip: Unify primary,secondary tests (primary UDNs use managedTap)

- .github/workflows/publish-img.yaml
enable build process to support various architectures (e.g., amd64, arm64, and s390x) for ipam-controller.
Currently, the ipam-controller image is supported only on the amd64 architecture. You can find the image here: [ipam-controller image](https://github.com/kubevirt/ipam-extensions/pkgs/container/ipam-controller). With the changes from these PRs, we are now able to build and push an image that supports multiple platforms.
Fixes #
```release-note
None
```
> Add multiplatform support for ipam-controller image.

- Makefile
- test/e2e/e2e_suite_test.go
- test/e2e/persistentips_test.go
- test/env/generate.go
This PR is running the e2e tests in parallel, as tests should be independent of each other. 
The amount of threads depends on the number of CPUs available in the machine running the CI.
Running it on the PR should increase CI time, and potentially expose bugs.
e2e run example: `E2E_TEST_ARGS='--focus="should keep ips after live migration"' make test-e2e`
Fixes #
```release-note
NONE
```
> test/e2e: Run in parallel

- test/e2e/persistentips_test.go
- test/env/env.go
1. Following the [change](https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4854) on ovn-kubevernets, this PR aligns the binding name to `l2bridge`.
2. Following the [change](https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4912) on ovn-kubevernets, this PR aligns the namespace to have the primary UDN label.
Fixes #
```release-note
NONE
```
> e2e, primaryUDN: Align with OVNK changes

- config/manager/manager.yaml
- dist/install.yaml
control-plane components such as ipam-ext Deployment should not have memory/cpu limit.
This PR removes the limits.
Also, Increasing memory request to those [requested](https://github.com/k8snetworkplumbingwg/kubemacpool/blob/main/config/release/kubemacpool.yaml#L301) by similar components like kubemacpool.
Fixes #
```release-note
NONE
```
> config/manager, ipam-ext Deployment: Remove limits, Increase reqeusts

- pkg/config/types.go
Until now, a NAD with empty config, was considered invalid,
causing an error / rejecting it on the webhook.
Istio creates such NADs, so we can't consider them as fatal,
once we list all the NADs in a namespace.
Otherwise the webhook will block VM creation [1] in case it uses
such NAD.
Therefore just ignore those.
```
[1] virtualmachine-controller    Error creating pod: admission webhook "ipam-claims.k8s.cni.cncf.io" denied the request: failed to extract CNI configuration from NAD: unexpected end of JSON input
```
Example of resource that create such NAD:
```
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
name: default
namespace: istio-system
spec:
members:
- non-udn-ns
```
**Which issue(s) this PR fixes** *(optional, in `fixes …
> nad: Skip NADs with empty config

- .github/workflows/publish-img.yaml
enable build process to support various architectures (e.g., amd64, arm64, and s390x) for passt binding.
This PR enables multi-architecture support for the passthrough binding CNI(https://github.com/kubevirt/ipam-extensions/pkgs/container/passt-binding-cni) . Previously, we added multi-arch support for all CNIs used in CNAO . However, passthrough binding currently lacks multi-arch support, and since CNAO still uses it when deploying the IPAM controller CNI, this causes failures. To prevent these failures, we are implementing this temporary workaround till we remove passt binding.
To be more precise, this process will build a multi-architecture image, but the binary inside will still be for amd64.
please note that currently, KubeVirt is only …
> Add multi-arch support for passt binding.

- .github/workflows/publish-img.yaml
last merged PR ([#94](https://github.com/kubevirt/ipam-extensions/pull/94))  removed multi-arch support for the ipam-controller ([v0.2.3](https://github.com/kubevirt/ipam-extensions/pkgs/container/ipam-controller/381539608?tag=v0.2.3)).
We are re-adding the BUILD_PLATFORM environment variable to enable multi-architecture builds.
Fixes #
```release-note
None
```
> Add build-platforms env variable for multi-arch build.

- config/manager/manager.yaml
- dist/install.yaml
To comply with best practices, all the containers in all the pods, must set the TerminationMessagePolicy field to FallbackToLogsOnError [0]
[0]
https://github.com/redhat-best-practices-for-k8s/certsuite/blob/main/CATALOG.md#observability-termination-policy
Fixes #
checked manually:
```
[root@hades04 ipam-extensions]# kubectl get pod -nkubevirt-ipam-controller-system -ojson | jq .items[0].spec.containers[0].terminationMessagePolicy
"FallbackToLogsOnError"
```
```release-note
NONE
```
> Set container's TerminationMessagePolicy to FallbackToLogsOnError

- config/default/kustomization.yaml
- config/networkpolicy/allow-egress-dns.yaml
- config/networkpolicy/allow-egress-kube-apiserver.yaml
- config/networkpolicy/allow-ingress-to-service.yaml
- config/networkpolicy/kustomization.yaml
- dist/install.yaml
- hack/cluster.sh
- hack/install-deny-all-net-pol.sh
In a scenario where a cluster networking has been hardened and futures
a default deny-all network policy that affects kubevirt-ipam-controller namespace,
it will not be able to operate properly.
This PR introduce network-policies for the project allowing kubevirt-ipam-controller to operate,
complying with restrictions in form of deny all network-policy.
In order to have coverage for the introduced network-policies, and additional deny-all network-policies is installed as part of the cluster-sync flow.
Having a deny-all network-policy installed, allow the introduced network-policies to be tested in a development and test environments, locally and CI.
```release-note
config: Introduce …
```
> Add Network policies

- Makefile
- pkg/claims/claims.go
- pkg/vminetworkscontroller/vmi_controller_test.go
- pkg/vmnetworkscontroller/vm_controller_test.go
- test/e2e/persistentips_test.go
Format new ipamclaims keys to follow kubernetes CRD name restrictions
Fixes #https://issues.redhat.com/browse/CNV-62286
There is no problems from upgrades since already created ipamclaims have a proper name that do not need formatting.
```release-note
claims: Format key to domain name
```
> claims: Format key to domain name

- .github/workflows/checks.yaml
- .github/workflows/publish-img.yaml
- Makefile
- pkg/claims/claims.go
- pkg/vminetworkscontroller/vmi_controller_test.go
- pkg/vmnetworkscontroller/vm_controller_test.go
- test/e2e/persistentips_test.go
Format new ipamclaims keys to follow kubernetes CRD name restrictions
Fixes #https://issues.redhat.com/browse/CNV-62286
There is no problems from upgrades since already created ipamclaims have a proper name that do not need formatting.
```release-note
claims: Format key to domain name
```
> [release-0.2.1] claims: Format key to domain name

- .github/workflows/checks.yaml
- .github/workflows/publish-img.yaml
- Makefile
- config/manager/kustomization.yaml
- dist/install.yaml
- hack/sanitize-branch.sh
- Add branch-based image tagging using sanitized branch names
- Create reusable hack/sanitize-branch.sh script for branch name sanitization
- Use github.ref_type and github.ref_name for cleaner conditional logic
- Split image pushing into separate steps for better control:
- Push branch-based tags for all branch pushes
- Push :latest tag only for main branch pushes
- Keep stable tag pushing for release tags
- Update both publish-img.yaml and checks.yaml workflows to use branch-based tagging
- Maintain backward compatibility with existing :latest references
- Update Makefile to use full registry path for consistency
- Generate branch-specific manifests for non-release pushes
The sanitization script handles Docker tag requirements:
- Converts to …
> [release-0.2.4] feat: use branch name for image tagging with improved workflow logic

- .github/workflows/checks.yaml
- .github/workflows/publish-img.yaml
- Makefile
- config/manager/kustomization.yaml
- dist/install.yaml
- hack/sanitize-branch.sh
- Add branch-based image tagging using sanitized branch names
- Create reusable hack/sanitize-branch.sh script for branch name sanitization
- Use github.ref_type and github.ref_name for cleaner conditional logic
- Split image pushing into separate steps for better control:
- Push branch-based tags for all branch pushes
- Push :latest tag only for main branch pushes
- Keep stable tag pushing for release tags
- Update both publish-img.yaml and checks.yaml workflows to use branch-based tagging
- Maintain backward compatibility with existing :latest references
- Update Makefile to use full registry path for consistency
- Generate branch-specific manifests for non-release pushes
The sanitization script handles Docker tag requirements:
- Converts to …
> [releas-0.2.1] feat: use branch name for image tagging with improved workflow logic

- Makefile
- test/e2e/persistentips_test.go
This PR is fixing several issuw causing the e2e lane to fail:
- conversion issue that caused e2e tests to panic.
- virtctl not installed
Fixes #
```release-note
NONE
```
> test: Fix broken CI lane

- .github/workflows/nightly.yaml
ipam-ext repo is dependant of various external dependencies, from changes in OVNK deployment to gitActions runner images changing. Things may break even if we didn't do anything on the repo, and we want to know when that happens.
Introducing a nightly run for that end.
Fixes #
```release-note
NONE
```
> ci: add nightly e2e test workflow with failure notifications

- go.mod
- go.sum
- vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1/types.go
- vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/utils/net-attach-def.go
- vendor/modules.txt
This PR is bumping nad-client to v1.7.7 as ipam-extentions needs to align with new multus-default-network logic.
Fixes #
```release-note
NONE
```
> vendor: Bump network-attachment-definition-client to v1.7.7
